#!/usr/bin/env ruby

$:<< File.join(File.dirname(__FILE__), '../ext/rs_232')
$:<< File.join(File.dirname(__FILE__), '../lib')

require 'irb'
require 'irb/completion'
require 'rs_232'

$stdout.puts "Interactive session loaded. (Rs-232 v#{Rs232::VERSION})"
IRB.start

