#!/usr/bin/env ruby
%w(lib examples).each do |path|
  expanded_path = File.expand_path("../../#{path}", __FILE__)
  $LOAD_PATH.unshift(expanded_path) unless $LOAD_PATH.include? expanded_path
end

require 'irb'
require 'irb/completion'
require 'rs_232'

$stdout.puts "Interactive session loaded. (Rs-232 v#{Rs232::VERSION})"
IRB.start
